[cipd] Try to bootstrap CIPD from scratch if selfupdate fails.
When updating the CIPD client to be identified by SHA256 hash, old clients (that
have no idea about SHA256) fail during 'selfupdate'.

We'll roll our SHA256 support in two stages:
  1. Deploy new client that understand SHA256 using its SHA1 name, so
     self-update from old clients works.
  2. Deploy same (or newer) client using its SHA256 name. This would work since
     the client doing the self-update already understands SHA256 at this point.

But we can't guarantee that ALL depot_tools deployments will update through
stages (1) and (2) sequentially. Some of them may skip (1) and end-up directly
in (2), failing on 'selfupdate'.

This CL makes sure they can recover from this state by rebootstraping the client
from scratch (this works with SHA256 hashes).

R=nodir@chromium.org, iannucci@chromium.org
BUG=821194

Change-Id: I27dece19e0305b5b2d6f8b0130631c1bf5f6499c
Reviewed-on: https://chromium-review.googlesource.com/1149454
Commit-Queue: Vadim Shtayura <vadimsh@chromium.org>
Reviewed-by: Robbie Iannucci <iannucci@chromium.org>

diff --git a/cipd b/cipd
--- a/cipd
+++ b/cipd
@@ -71,14 +71,15 @@ CLIENT="$MYPATH/.cipd_client"
 
 USER_AGENT="depot_tools/$(git -C $MYPATH rev-parse HEAD 2>/dev/null || echo "???")"
 
-if [ ! -e "$CLIENT" ]; then
+# clean_bootstrap bootstraps the client from scratch using 'curl' or 'wget'.
+function clean_bootstrap() {
   echo "Bootstrapping cipd client for ${PLAT}-${ARCH} from ${URL}..."
 
   # Download the client into a temporary file, then move it into the final
   # location atomically.
   #
   # This wonky tempdir method works on Linux and Mac.
-  CIPD_CLIENT_TMP=$(\
+  local CIPD_CLIENT_TMP=$(\
     mktemp -p "$MYPATH" 2>/dev/null || \
     mktemp "$MYPATH/.cipd_client.XXXXXXX")
 
@@ -105,13 +106,26 @@ if [ ! -e "$CLIENT" ]; then
   set +e
   mv "$CIPD_CLIENT_TMP" "$CLIENT"
   set -e
+}
+
+function self_update() {
+  "$CLIENT" selfupdate -version "$CIPD_CLIENT_VER" -service-url "$CIPD_CLIENT_SRV"
+}
+
+if [ ! -x "$CLIENT" ]; then
+  clean_bootstrap
 fi
 
 export CIPD_HTTP_USER_AGENT_PREFIX=$USER_AGENT
-if ! "$CLIENT" selfupdate -version "$CIPD_CLIENT_VER" ; then
-  echo -n "[31;1mselfupdate failed:[0;1m " 1>&2
-  echo "run \`CIPD_HTTP_USER_AGENT_PREFIX=$USER_AGENT/manual $CLIENT selfupdate -version '$CIPD_CLIENT_VER'\` to diagnose" 1>&2
-  echo "[0m" 1>&2
+if ! self_update ; then
+  echo -n "[31;1mCIPD selfupdate failed. " 1>&2
+  echo "Trying to bootstrap the CIPD client from scratch... [0m" 1>&2
+  clean_bootstrap
+  if ! self_update ; then  # need to run it again to setup .cipd_version file
+    echo -n "[31;1mBootstrap from scratch failed, something is seriously broken[0m " 1>&2
+    echo "run \`CIPD_HTTP_USER_AGENT_PREFIX=$USER_AGENT/manual $CLIENT selfupdate -version '$CIPD_CLIENT_VER'\` to diagnose if this is repeating." 1>&2
+    echo "[0m" 1>&2
+  fi
 fi
 
 # CygWin requires changing absolute paths to Windows form. Relative paths
