Support the analyzer on all targets.
Move the analyzer setup to process_toolchain() in configure to
ensure the {CXX,LD}FLAGS are picked up for all targets.

Change-Id: I037f52406c19a42ddd848adad2f43d3a49b00ded

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -648,14 +648,6 @@ EOF
     check_header unistd.h # for sysconf(3) and friends.
 
     check_header aom/aom_integer.h -I${source_path} && enable_feature aom_ports
-    enabled analyzer && soft_enable wxwidgets
-    if enabled wxwidgets; then
-      if ! wx-config --version > /dev/null; then
-        die "Couldn't find wx-config"
-      fi
-      WX_CXXFLAGS=$(wx-config --cppflags)
-      WX_LDFLAGS=$(wx-config --libs)
-    fi
 }
 
 process_toolchain() {
@@ -697,6 +689,16 @@ process_toolchain() {
         # ICC has a number of floating point optimizations that we disable
         # in favor of deterministic output WRT to other compilers
         add_cflags -fp-model precise
+    fi
+
+    if enabled analyzer; then
+      soft_enable wxwidgets
+      if ! wx-config --version > /dev/null; then
+        die "Couldn't find wx-config"
+      fi
+
+      add_cxxflags_only $(wx-config --cppflags)
+      add_extralibs $(wx-config --libs)
     fi
 
     # Enable extra, harmless warnings. These might provide additional insight
