update_depot_tools: make cipd_bin_setup failures fatal
This should make them more noticeable.

Bug: 762568
Change-Id: Ibd4ca4dc34d36aec5773d28454d134c909cc78dc
Reviewed-on: https://chromium-review.googlesource.com/653157
Reviewed-by: Daniel Jacques <dnj@chromium.org>
Commit-Queue: Paweł Hajdan Jr. <phajdan.jr@chromium.org>

diff --git a/update_depot_tools b/update_depot_tools
--- a/update_depot_tools
+++ b/update_depot_tools
@@ -121,7 +121,10 @@ if [ "X$DEPOT_TOOLS_UPDATE" != "X0" ]; then
 
   # Sync CIPD and CIPD client tools.
   source "$base_dir/cipd_bin_setup.sh"
-  cipd_bin_setup
+  cipd_bin_setup || {
+    echo "CIPD bootstrap failed"
+    exit 1
+  }
 
   find "$base_dir" -iname "*.pyc" -exec rm -f {} \;
 fi
