Make bump_compiler_version die if runner.jar isn't rebuilt
TBR=jlklein@chromium.org
BUG=none
TEST=try to compile inevitably stale code without success :)

NOTRY=true

Review URL: https://codereview.chromium.org/1314673005

Cr-Commit-Position: refs/heads/master@{#346131}

Former-commit-id: 5ed8a8597797e6c286eb7a5b254e090e88956683

diff --git a/third_party/closure_compiler/bump_compiler_version b/third_party/closure_compiler/bump_compiler_version
--- a/third_party/closure_compiler/bump_compiler_version
+++ b/third_party/closure_compiler/bump_compiler_version
@@ -50,6 +50,11 @@ if [[ "${new_compiler_version}" != "${previous_compiler_version}" ]]; then
 
   echo "Compiler version changed; re-building runner.jar"
   "${SCRIPT_DIR}/runner/build_runner_jar.py"
+  if [[ "$?" -ne 0 ]]; then
+    echo "Failed to build runner.jar, roll unsuccessful"
+    cleanup
+    exit 1
+  fi
 
   compiler_jar_range="compiler.jar: ${previous_compiler_version} -> ${new_compiler_version}"
 fi
