Stop checking the compiler version.
The version is just a function of the commit it was built from, and we're already including that information

BUG=

Review URL: https://codereview.chromium.org/1403813004

Cr-Commit-Position: refs/heads/master@{#354130}

Former-commit-id: 4ab6f2a7971026301f4b475f1ffd95725611c7cc

diff --git a/third_party/closure_compiler/roll_closure_compiler b/third_party/closure_compiler/roll_closure_compiler
--- a/third_party/closure_compiler/roll_closure_compiler
+++ b/third_party/closure_compiler/roll_closure_compiler
@@ -18,10 +18,6 @@ cleanup() {
   rm -rf "${TEMP_DIR}"
 }
 
-get_compiler_version() {
-  java -jar "${1}" --version | grep ^Version: | cut -d' ' -f2
-}
-
 get_externs_sha1() {
   sha1sum "${EXTERNS_PATH}" | cut -d' ' -f1
 }
@@ -29,7 +25,6 @@ get_externs_sha1() {
 trap cleanup SIGINT SIGHUP SIGTERM
 
 old_head=$(egrep -o '^Revision: [0-9a-f]{5,40}$' "${README}" | cut -d' ' -f2)
-old_compiler_version=$(get_compiler_version ${COMPILER_PATH})
 old_externs_sha1=$(get_externs_sha1)
 
 cd "${TEMP_DIR}"
@@ -41,7 +36,11 @@ cd closure-compiler
 
 new_head=$(git rev-parse HEAD)
 
-if [[ "${new_head}" != "${old_head}" ]]; then
+if [[ "${new_head}" == "${old_head}" ]]; then
+  echo "No closure-compiler changes since last roll. Nothing to do."
+  cleanup
+  exit 0
+else
   head_range=$(cat <<EOT
 Change log:
 https://github.com/google/closure-compiler/compare/${old_head}...${new_head}
@@ -58,20 +57,14 @@ if [[ "$?" -ne 0 ]]; then
   exit 1
 fi
 
-new_compiler_version=$(get_compiler_version "build/compiler.jar")
+cp build/compiler.jar "${COMPILER_PATH}"
 
-if [[ "${new_compiler_version}" != "${old_compiler_version}" ]]; then
-  cp build/compiler.jar "${COMPILER_PATH}"
-
-  echo "Compiler version changed; re-building runner.jar"
-  "${SCRIPT_DIR}/runner/build_runner_jar.py"
-  if [[ "$?" -ne 0 ]]; then
-    echo "Failed to build runner.jar, roll unsuccessful"
-    cleanup
-    exit 1
-  fi
-
-  jar_range="compiler.jar: ${old_compiler_version} -> ${new_compiler_version}"
+echo "Re-building runner.jar"
+"${SCRIPT_DIR}/runner/build_runner_jar.py"
+if [[ "$?" -ne 0 ]]; then
+  echo "Failed to build runner.jar, roll unsuccessful"
+  cleanup
+  exit 1
 fi
 
 (cat <<EOT && cat contrib/externs/chrome_extensions.js) > "${EXTERNS_PATH}"
@@ -108,10 +101,6 @@ echo "@  closure-compiler.git HEAD:"
 echo "@    Old: ${old_head}"
 echo "@    New: ${new_head}"
 echo "@"
-echo "@  Compiler version:"
-echo "@    Old: ${old_compiler_version}"
-echo "@    New: ${new_compiler_version}"
-echo "@"
 echo "@  Externs SHA1:"
 echo "@    Old: ${old_externs_sha1}"
 echo "@    New: ${new_externs_sha1}"
@@ -119,23 +108,16 @@ echo "@"
 echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
 echo
 
-# I assume HEAD is constantly changing, but it may not necessarily affect
-# either the jar or the externs. Only roll when it matters to us.
-if [[ -z "${jar_range}" ]] && [[ -z "${externs_range}" ]]; then
-  echo "Nothing to update"
-else
-  sed -i "s/^Revision: ${old_head}$/Revision: ${new_head}/" "${README}"
+sed -i "s/^Revision: ${old_head}$/Revision: ${new_head}/" "${README}"
 
-  echo "git commit -a -m 'Roll closure compiler"
-  echo
-  if [[ ! -z "${head_range}" ]]; then echo "${head_range}"; echo; fi
-  if [[ ! -z "${jar_range}" ]]; then echo "${jar_range}"; fi
-  if [[ ! -z "${externs_range}" ]]; then echo "${externs_range}"; fi
-  echo
-  echo "TBR="
-  echo "BUG='"
-  echo
-  echo "git cl upload"
-fi
+echo "git commit -a -m 'Roll closure compiler"
+echo
+echo "${head_range}"
+if [[ ! -z "${externs_range}" ]]; then echo "${externs_range}"; fi
+echo
+echo "TBR="
+echo "BUG='"
+echo
+echo "git cl upload"
 
 cleanup
