run_tests: make log management more reliable
First let's use a tempname base that allows us to track it back cleanly
to this script so devs know what is orphaning things in /tmp.

Next, use the same tempfile name as a base for all logs rather than each
test getting its own.  This way when we kill the script early with ^C,
we don't leak logs randomly.  We can glob all of them at the same time.

Finally, if the user does kill us, still output the failing logs at the
end.  This way when you see a test fail early, you can halt things and
still get the output.

BUG=None
TEST=`./run_tests` works
TEST=`./run_tests` and hitting ^C works (i see the errors, and the logs are cleaned up)

Change-Id: Idfeda230d73cf16ab98fa0d769b12c530dc887b7
Reviewed-on: https://chromium-review.googlesource.com/167790
Reviewed-by: Marc MERLIN <merlin@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>

diff --git a/buildbot/run_tests b/buildbot/run_tests
--- a/buildbot/run_tests
+++ b/buildbot/run_tests
@@ -10,7 +10,7 @@ CHROOT_CHROMITE=../../chromite
 
 set -eu
 
-LOGFILE="$(mktemp)"
+LOGFILE="$(mktemp -t buildbot.run_tests.XXXXXX)"
 
 # Helper function to add failed logs/tests to be printed out later.
 # $1 test that failed.
@@ -18,35 +18,30 @@ LOGFILE="$(mktemp)"
 append_failed_test() {
   echo "ERROR: Unittest $1 failed.  Log will be output at end of run!!!"
 
-  cat << EOF >> "${LOGFILE}.$$"
+  cat - "$2" <<EOF >>"${LOGFILE}.err.${BASHPID}"
 
 FAIL: Unittest $1 failed output:
 
-$(<"$2")
 EOF
-  rm -f "$2"
 }
 
 # Wrapper to run unittest.  Hides output unless test fails.
 # $1 test to run.  Must be in chromite/buildbot.
 # $2 If set, run inside the chroot.
 run_test() {
-  local log_file="$(mktemp)"
+  local log_file="${LOGFILE}.tmp.${BASHPID}"
   local special="${special_tests[$1]:-}"
   local starttime="$(date +%s%N)"
 
   if [[ "${special}" == "skip" ]]; then
     echo "Skipping unittest $1"
-    rm "${log_file}"
     return
   elif [[ "${special}" == "outside" && -f /etc/debian_chroot ]]; then
     echo "Skipping unittest $1 because it must run outside the chroot."
-    rm "${log_file}"
     return
   elif [[ "${special}" == "inside" && ! -f /etc/debian_chroot ]]; then
     if ${SKIP_CHROOT_TESTS}; then
       echo "Skipping unittest $1 because it must run inside the chroot"
-      rm "${log_file}"
       return
     else
       echo "Starting unittest $1 inside the chroot"
@@ -147,6 +142,24 @@ cleanup() {
   # Set of a hard kill timer after a while.
   delayed_kill &
   wait ${children[*]}
+  show_logs
+}
+
+show_logs() {
+  cat "${LOGFILE}".err.* > "${LOGFILE}" 2>/dev/null || :
+
+  rm -f "${LOGFILE}".*
+  if [[ -s ${LOGFILE} ]]; then
+    cat "${LOGFILE}"
+    echo
+    echo
+    echo "FAIL: The following tests failed:"
+    sed -nre '/^FAIL:/s/^FAIL: Unittest (.*) failed output:/\1/p' "${LOGFILE}"
+    rm -f "${LOGFILE}"
+    exit 1
+  fi
+
+  rm -f "${LOGFILE}"
 }
 
 trap cleanup INT TERM
@@ -159,17 +172,5 @@ done
 wait ${children[*]}
 trap - INT TERM
 
-cat "${LOGFILE}".* > "${LOGFILE}" 2>/dev/null || :
-rm -f "${LOGFILE}".*
-if [[ $(wc -c "${LOGFILE}" |cut -f1 -d' ') -gt 0 ]]; then
-  cat "${LOGFILE}"
-  echo
-  echo
-  echo "FAIL: The following tests failed:"
-  sed -nre '/^FAIL:/s/^FAIL: Unittest (.*) failed output:/\1/p' "${LOGFILE}"
-  rm -f "${LOGFILE}"
-  exit 1
-fi
-
-rm -f "${LOGFILE}"
+show_logs
 echo "All tests succeeded!"
