build_annotator: fix table rendering
This CL makes a small css fix that allows tables to render correctly
again on the annotator app.

In order to deploy this change, this CL also fixes some of the
deployment scripts for the annotator app. In particular, we:
 - upgrade to the newest version of the appendine sdk, as the old sdk is
   deprecated and no longer hosted.
 - allow our carried patches (which fail to apply) to silently fail to
   apply (they are apparently only necessary for local running)
 - allow imports of appengine-forbidden module to silently do nothing
   (these new transitive dependencies are being imported as a result of
   some unrelated chromite import; it will require a major refactor to
   avoid importing them)

BUG=chromium:598823, chromium:597819
TEST=deployed to debug instance, see go/chromiumos-build-annotator-dbg.
Tables are correctly rendered.

Change-Id: I37c2e40593b0360de5ce6f7d0f7108c1167b8239
Reviewed-on: https://chromium-review.googlesource.com/335615
Tested-by: Aviv Keshet <akeshet@chromium.org>
Reviewed-by: Kevin Cheng <kevcheng@chromium.org>

diff --git a/appengine/cq_stats/appengine_sdk_mod b/appengine/cq_stats/appengine_sdk_mod
--- a/appengine/cq_stats/appengine_sdk_mod
+++ b/appengine/cq_stats/appengine_sdk_mod
@@ -20,8 +20,7 @@ fi
 
 for sdk_patch in "${SDK_PATCHES[@]}"; do
   echo "Applying ${sdk_patch} to ${APPENGINE_SDK_DIR}"
-  if ! patch -d "${APPENGINE_SDK_DIR}" -p 1 < "${sdk_patch}"; then
-    error "Failed to apply patch ${sdk_patch}. Bailing."
-    exit ${E_GENERAL}
+  if ! patch -t -d "${APPENGINE_SDK_DIR}" -p 1 < "${sdk_patch}"; then
+    error "Failed to apply patch ${sdk_patch}. Trying to continue anyway."
   fi
 done
