Snapshot 104.0.5112.0
Change-Id: Ib69b7582a1c8c312b365858fda9eb30137cf590a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3695986
Bot-Commit: Chrome Release Bot (LUCI) <chrome-official-brancher@chops-service-accounts.iam.gserviceaccount.com>
Cr-Commit-Position: refs/branch-heads/5112@{#1}
Cr-Branched-From: b13d3fe7b3c47a56354ef54b221008afa754412e-refs/heads/main@{#1012729}

diff --git a/src/third_party/depot_tools/update_depot_tools b/src/third_party/depot_tools/update_depot_tools
--- a/src/third_party/depot_tools/update_depot_tools
+++ b/src/third_party/depot_tools/update_depot_tools
@@ -130,6 +130,9 @@ if [ "X$DEPOT_TOOLS_UPDATE" != "X0" ]; then
     cd "$base_dir"
     update_git_repo
     cd - > /dev/null
+  else
+    echo "Warning: Your depot_tools directory does not appear to be a git repository, and cannot be updated." 1>&2
+    echo "Consider deleting your depot_tools directory and following the instructions at https://www.chromium.org/developers/how-tos/install-depot-tools/ to reinstall it." 1>&2
   fi
 
   # Sync CIPD-boostrapped packages.
